/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkfft_MainService */

#ifndef _Included_com_example_ndkfft_MainService
#define _Included_com_example_ndkfft_MainService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkfft_MainService
 * Method:    getResultFromNDK
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkfft_MainService_getResultFromNDK
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
