/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkfft_MainService_LocalBinder */

#ifndef _Included_com_example_ndkfft_MainService_LocalBinder
#define _Included_com_example_ndkfft_MainService_LocalBinder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
